// let students = [
//   'Diane',
//   'Temitope',
//   'Julia',
//   'Lynette',
//   'Aki',
//   'Jenna',
//   'Douglas',
//   'Olusola',
//   'Jonatha',
//   'Efa',
//   'Huang',
//   'Erik',
//   'Zachary',
//   'Teo',
//   'Ann',
//   'Fabrice',
//   'Christopher',
//   'Kenneth',
//   'Matthew',
//   'Shehroze',
//   'Jonathan',
//   'Efa',
//   'Huang',
//   'Sarah',
//   'Sabrina',
//   'Quenton',
//   'Mariluz',
//   'Carl',
//   'Cedra',
// ];

let students = [
    { name: 'Diane', grade: 100, coolLevel: 'extremely high' },
    { name: 'Temitope', grade: 100, coolLevel: 'extremely high' },
    { name: 'Julia', grade: 100, coolLevel: 'extremely high' },
    { name: 'Lynette', grade: 100, coolLevel: 'extremely high' },
    { name: 'Aki', grade: 100, coolLevel: 'extremely high' },
    { name: 'Jenna', grade: 100, coolLevel: 'extremely high' },
    { name: 'Douglas', grade: 100, coolLevel: 'extremely high' },
    { name: 'Olusola', grade: 100, coolLevel: 'extremely high' },
    { name: 'Jonathan', grade: 100, coolLevel: 'extremely high' },
    { name: 'Efa', grade: 100, coolLevel: 'extremely high' },
    { name: 'Huang', grade: 100, coolLevel: 'extremely high' },
    { name: 'Erik', grade: 100, coolLevel: 'extremely high' },
    { name: 'Zachary', grade: 100, coolLevel: 'extremely high' },
    { name: 'Teo', grade: 100, coolLevel: 'extremely high' },
    { name: 'Ann', grade: 100, coolLevel: 'extremely high' },
    { name: 'Fabrice', grade: 100, coolLevel: 'extremely high' },
    { name: 'Christopher', grade: 100, coolLevel: 'extremely high' },
    { name: 'Kenneth', grade: 100, coolLevel: 'extremely high' },
    { name: 'Matthew', grade: 100, coolLevel: 'extremely high' },
    { name: 'Shehroze', grade: 100, coolLevel: 'extremely high' },
    { name: 'Jonathan', grade: 100, coolLevel: 'extremely high' },
    { name: 'Efa', grade: 100, coolLevel: 'extremely high' },
    { name: 'Huang', grade: 100, coolLevel: 'extremely high' },
    { name: 'Sarah', grade: 100, coolLevel: 'extremely high' },
    { name: 'Sabrina', grade: 100, coolLevel: 'extremely high' },
    { name: 'Quenton', grade: 100, coolLevel: 'extremely high' },
    { name: 'Mariluz', grade: 100, coolLevel: 'extremely high' },
    { name: 'Carl', grade: 100, coolLevel: 'extremely high' },
    { name: 'Cedra', grade: 100, coolLevel: 'extremely high' },
  ];

module.exports = students